//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NightOut
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Performers = new HashSet<Performer>();
            this.Places = new HashSet<Place>();
        }
    
        public int EventID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TimeDate { get; set; }
        public string Price { get; set; }
        public string OpeningHours { get; set; }
    
        public virtual ICollection<Performer> Performers { get; set; }
        public virtual ICollection<Place> Places { get; set; }
    }
}
